#Spring Properties
spring:
  banner:
    location: classpath:/banner/banner.txt

  #database connector
  datasource:
    url: jdbc:mysql://localhost:3306/db_springboot_backend?useSSL=false
    username: root
    password: Edroot6792.
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug