INSERT INTO regiones (id, nombre) VALUES (1, "Nortemérica");
INSERT INTO regiones (id, nombre) VALUES (2,"Centroamérica");
INSERT INTO regiones (id, nombre) VALUES (3,"Sudamérica");
INSERT INTO regiones (id, nombre) VALUES (4,"Europa");
INSERT INTO regiones (id, nombre) VALUES (5,"Asía");
INSERT INTO regiones (id, nombre) VALUES (6,"Africa");
INSERT INTO regiones (id, nombre) VALUES (7,"Ocenia");
INSERT INTO regiones (id, nombre) VALUES (8,"Antártida");

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (1,'Eduardo', 'Ocampo', 'ed.develit@gmail.com', '2019-01-10');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3,'Victor', 'Mendoza', 'victor@gmail.com', '2019-05-22');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5,'Antonio', 'Perez', 'antonio.perez@gmail.com', '2019-03-25');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8,'Luis', 'Ruiz', 'quirozstorm@gmail.com', '2019-05-29');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3,'Victor', 'Mendoza', 'victor@gmail.com', '2019-05-22');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5,'Antonio', 'Perez', 'antonio.perez@gmail.com', '2019-03-25');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8,'Luis', 'Ruiz', 'quirozstorm@gmail.com', '2019-05-29');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3,'Victor', 'Mendoza', 'victor@gmail.com', '2019-05-22');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5,'Antonio', 'Perez', 'antonio.perez@gmail.com', '2019-03-25');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8,'Luis', 'Ruiz', 'quirozstorm@gmail.com', '2019-05-29');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (3,'Victor', 'Mendoza', 'victor@gmail.com', '2019-05-22');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (5,'Antonio', 'Perez', 'antonio.perez@gmail.com', '2019-03-25');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES (8,'Luis', 'Ruiz', 'quirozstorm@gmail.com', '2019-05-29');